service: process-image

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.ts
    packager: yarn
    includeModules: true # Enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'development'}
  memorySize: 512
  environment:
    NODE_ENV: ${opt:stage, 'local'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectVersionTorrent
        - s3:GetObjectVersionTagging
        - s3:GetObjectTagging
        - s3:GetObjectVersionForReplication
      Resource:
        - "arn:aws:s3:::hollowverse-photos-${opt:stage, 'development'}/*"
    - Effect: Allow
      Action:
        - s3:DeleteObjectTagging
        - s3:PutObject
        - s3:DeleteObjectVersion
        - s3:PutObjectVersionTagging
        - s3:PutObjectTagging
        - s3:DeleteObjectVersionTagging
        - s3:DeleteObject
      Resource:
        - "arn:aws:s3:::hollowverse.public-test/*"
    - Effect: Allow
      Action:
        - rekognition:DetectLabels
        - rekognition:GetCelebrityRecognition
        - rekognition:DetectFaces
        - rekognition:GetFaceDetection
        - rekognition:RecognizeCelebrities
        - rekognition:CompareFaces
        - rekognition:GetCelebrityInfo
        - rekognition:GetLabelDetection
      Resource: "*"

functions:
  processImage:
    handler: src/processImage.processImage
    events:
      - s3:
          bucket: hollowverse-photos-${opt:stage, 'development'}
          event: s3:ObjectCreated:*
          rules:
            - prefix: notable-people/
      - s3:
          bucket: hollowverse-photos-${opt:stage, 'development'}
          event: s3:ObjectRemoved:*
          rules:
            - prefix: notable-people/

package:
  include:
    - src/**
    - secrets/**
  exclude:
    - .webpack

