service: process-image

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.ts
    packager: yarn
    includeModules: true # Enable auto-packing of external modules

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  memorySize: 128
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    STAGE: ${self:provider.stage}
    SOURCE_BUCKET_NAME: hollowverse.photos-unprocessed-${opt:stage, 'development'}
    TARGET_BUCKET_NAME: hollowverse.photos-processed-${opt:stage, 'development'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: "*"
      Conditions:
        StringEquals:
          SecretId:
            - ${self:provider.stage}/cloudinary/apiConfig
    - Effect: Allow
      Action:
        - s3:GetObject*
      Resource:
        - arn:aws:s3:::${self:provider.environment.SOURCE_BUCKET_NAME}/*
    - Effect: Allow
      Action:
        - s3:DeleteObject*
        - s3:PutObject*
      Resource:
        - arn:aws:s3:::${self:provider.environment.TARGET_BUCKET_NAME}/*

functions:
  processImage:
    handler: src/processImage.processImage
    events:
      - s3:
          bucket: ${self:provider.environment.SOURCE_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: notable-people/
      - s3:
          bucket: ${self:provider.environment.SOURCE_BUCKET_NAME}
          event: s3:ObjectRemoved:*
          rules:
            - prefix: notable-people/

package:
  include:
    - src/**
    - secrets/**
  exclude:
    - .webpack

